extends Node

const PlAYER_WALK_SPEED = 3.5
const PlAYER_SPRINT_SPEED = 5.0
const PLAYER_CRAWL_SPEED = 2.5
const PLAYER_HEADBOB_FREQ = 2.4
const PLAYER_HEADBOB_AMP = 0.05
const JUMP_VELOCITY = 3.0
const MOUSE_SENSITIVITY = 0.004
